'use strict';

let defaultOptions = ['contrast', 'mute', 'theme', 'colorize', 'colorize-bg', 'defer'];
let options = ['contrast', 'mute', 'theme', 'colorize', 'colorize-bg', 'defer', 'default'];

module.exports = {
	base: {
		type: 'object',
		properties: {
			identifier: {
				type: 'string',
				title: 'Identifier (scope: \'identifier\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 1,
			},
			variable: {
				type: 'string',
				title: 'Variables (scope: \'variable\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 2,
			},
			'class': {
				type: 'string',
				title: 'Class Names (scope: \'meta.class\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 3,
			},
			comment: {
				type: 'string',
				title: 'Comments (scope: \'comment\')',
				'default': 'contrast',
				'enum': defaultOptions,
				order: 4,
			},
			primitive: {
				type: 'string',
				title: 'Primitives (scope: \'primitive\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 5,
			},
			storage_modifier: {
				type: 'string',
				title: 'Storage modifiers (scope: \'storage.modifier\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 6,
			},
			storage_type: {
				type: 'string',
				title: 'Storage types (scope: \'storage.type\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 7,
			},
			support_type: {
				type: 'string',
				title: 'Support types (scope: \'support.type\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 8,
			},
			language: {
				type: 'string',
				title: 'Language elements (scope: \'language\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 9,
			},
			keyword: {
				type: 'string',
				title: 'Keywords (scope: \'keyword\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 10,
			},
			operator: {
				type: 'string',
				title: 'Operators (scope: \'operator\')',
				'default': 'mute',
				'enum': defaultOptions,
				order: 11,
			},
			punctuation: {
				type: 'string',
				title: 'Punctuation (scope: \'punctuation\')',
				'default': 'defer',
				'enum': defaultOptions,
				order: 12,
			},
			markup: {
				type: 'string',
				title: 'Markup (scope: \'markup\')',
				'default': 'defer',
				'enum': defaultOptions,
				order: 13,
			},
			string_quoted: {
				type: 'string',
				title: 'Quoted string constants (scope: \'string.quoted\')',
				'default': 'theme',
				'enum': defaultOptions,
				order: 14,
			},
			string_unquoted: {
				type: 'string',
				title: 'Unquoted string constants (scope: \'string.unquoted\')',
				'default': 'theme',
				'enum': defaultOptions,
				order: 15,
			},
			regexp: {
				type: 'string',
				title: 'Regular expressions (scope: \'regexp\')',
				'default': 'theme',
				'enum': defaultOptions,
				order: 16,
			},
			support_constant: {
				type: 'string',
				title: 'Support constants (scope: \'support.constant\')',
				'default': 'theme',
				'enum': defaultOptions,
				order: 17,
			},
			constant_numeric: {
				type: 'string',
				title: 'Numeric constants (scope: \'constant.numeric\')',
				'default': 'theme',
				'enum': defaultOptions,
				order: 18,
			},
			source: {
				type: 'string',
				title: 'Source (scope: \'source\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 19,
			},
			name: {
				type: 'string',
				title: 'Name (scope: \'name\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 20,
			},
			'attribute-name': {
				type: 'string',
				title: 'Attribute name (scope: \'attribute-name\')',
				'default': 'colorize',
				'enum': defaultOptions,
				order: 21,
			},
			everythingElse: {
				type: 'string',
				title: 'Everything else',
				'default': 'theme',
				'enum': defaultOptions,
				order: 22,
			},
		},
	},
	empty: {
		type: 'object',
		collapsed: true,
		properties: {
			enabled: {
				type: 'boolean',
				title: 'Enabled',
				'default': 'true',
				order: 0,
			},
			identifier: {
				type: 'string',
				title: 'Identifier (scope: \'identifier\')',
				'default': 'default',
				'enum': options,
				order: 1,
			},
			variable: {
				type: 'string',
				title: 'Variables (scope: \'variable\')',
				'default': 'default',
				'enum': options,
				order: 2,
			},
			'class': {
				type: 'string',
				title: 'Class Names (scope: \'meta.class\')',
				'default': 'default',
				'enum': options,
				order: 3,
			},
			comment: {
				type: 'string',
				title: 'Comments (scope: \'comment\')',
				'default': 'default',
				'enum': options,
				order: 4,
			},
			primitive: {
				type: 'string',
				title: 'Primitives (scope: \'primitive\')',
				'default': 'default',
				'enum': options,
				order: 5,
			},
			storage_modifier: {
				type: 'string',
				title: 'Storage modifiers (scope: \'storage.modifier\')',
				'default': 'default',
				'enum': options,
				order: 6,
			},
			storage_type: {
				type: 'string',
				title: 'Storage types (scope: \'storage.type\')',
				'default': 'default',
				'enum': options,
				order: 7,
			},
			support_type: {
				type: 'string',
				title: 'Support types (scope: \'support.type\')',
				'default': 'default',
				'enum': options,
				order: 8,
			},
			language: {
				type: 'string',
				title: 'Language elements (scope: \'language\')',
				'default': 'default',
				'enum': options,
				order: 9,
			},
			keyword: {
				type: 'string',
				title: 'Keywords (scope: \'keyword\')',
				'default': 'default',
				'enum': options,
				order: 10,
			},
			operator: {
				type: 'string',
				title: 'Operators (scope: \'operator\')',
				'default': 'default',
				'enum': options,
				order: 11,
			},
			punctuation: {
				type: 'string',
				title: 'Punctuation (scope: \'punctuation\')',
				'default': 'default',
				'enum': options,
				order: 12,
			},
			markup: {
				type: 'string',
				title: 'Markup (scope: \'markup\')',
				'default': 'default',
				'enum': options,
				order: 13,
			},
			string_quoted: {
				type: 'string',
				title: 'Quoted string constants (scope: \'string.quoted\')',
				'default': 'default',
				'enum': options,
				order: 14,
			},
			string_unquoted: {
				type: 'string',
				title: 'Unquoted string constants (scope: \'string.unquoted\')',
				'default': 'default',
				'enum': options,
				order: 15,
			},
			regexp: {
				type: 'string',
				title: 'Regular expressions (scope: \'regexp\')',
				'default': 'default',
				'enum': options,
				order: 16,
			},
			support_constant: {
				type: 'string',
				title: 'Support constants (scope: \'support.constant\')',
				'default': 'default',
				'enum': options,
				order: 17,
			},
			constant_numeric: {
				type: 'string',
				title: 'Numeric constants (scope: \'constant.numeric\')',
				'default': 'default',
				'enum': options,
				order: 18,
			},
			source: {
				type: 'string',
				title: 'Source (scope: \'source\')',
				'default': 'default',
				'enum': options,
				order: 19,
			},
			name: {
				type: 'string',
				title: 'Name (scope: \'name\')',
				'default': 'default',
				'enum': options,
				order: 20,
			},
			'attribute-name': {
				type: 'string',
				title: 'Attribute name (scope: \'attribute-name\')',
				'default': 'default',
				'enum': options,
				order: 21,
			},
			everythingElse: {
				type: 'string',
				title: 'Everything else',
				'default': 'default',
				'enum': options,
				order: 22,
			},
		},
	},
};
